name: Flutter 2 Apk Builder

on:
  workflow_dispatch:
    inputs:
      captcha:
        description: 'Enter the code 1234 to continue'
        required: true

permissions:
  contents: write

jobs:
  validate_and_build:
    runs-on: ubuntu-latest
    steps:
    - name: Validate static CAPTCHA
      run: |
        if [ "${{ github.event.inputs.captcha }}" != "1234" ]; then
          echo "❌ Incorrect CAPTCHA! Please enter 1234."
          exit 1
        fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Extract uploaded Flutter project
      run: |
        ZIP_FILE=$(find upload_project_here -maxdepth 1 -name '*.zip' | head -n 1)
        if [ -z "$ZIP_FILE" ]; then
          echo "❌ No ZIP file found in upload_project_here/"
          exit 1
        fi
        echo "Found ZIP: $ZIP_FILE"
        unzip "$ZIP_FILE" -d project

    - name: Create android/ folder
      run: |
        cd project
        flutter create .
        cp -r ../project/* ./

    - name: Get dependencies
      run: cd project && flutter pub get

    - name: Build APK
      run: cd project && flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-apk
        path: project/build/app/outputs/flutter-apk/app-release.apk

    - name: Notify success
      run: echo "✅ APK build complete! It will be auto-deleted after 20 minutes."

  cleanup:
    needs: validate_and_build
    runs-on: ubuntu-latest
    steps:
    - name: Wait and clean up
      run: |
        echo "Waiting 20 minutes before cleanup..."
        sleep 1200
        echo "Cleaning up ZIP and build files..."
        rm -rf upload_project_here/*.zip
        rm -rf project
